server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/demo_bank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:wTqmrp2YlzBoyMLsWIf4}
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

transaction-manager:
  upsert-url: ${TRANSACTION_MANAGER_UPSERT_URL:http://localhost:8181/api/fin-txt/upsert}
